version: '3'

services:
  app_image1:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
  app_image2:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5001:5000"
