version: '3'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    depends_on:
      - db
  db:
    image: "postgres:latest"
    environment:
      POSTGRES_DB: devops_db
      POSTGRES_USER: wojtek
      POSTGRES_PASSWORD: password