version: '3'

services:
  app:
    build:
      context: ./app
    ports:
      - "5000:5000"
    environment:
      - DATABASE_HOST=database
  database:
    image: postgres:latest
    volumes:
      - .database:/docker-entrypoint-initdb.d
    environment:
        POSTGRES_DB: devops_db
        POSTGRES_USER: wojtek
        POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
