version: '3'

services:
  app1:
    build:
      context: ./app
    ports:
      - "5000:5000"
    environment:
      - DATABASE_HOST=database
    volumes:
      - ./app:/app
    entrypoint: /app/entrypoint.sh
    restart: unless-stopped
  app2:
    build:
      context: ./app
    ports:
      - "5001:5000"
    environment:
      - DATABASE_HOST=database
    volumes:
      - ./app:/app
    entrypoint: /app/entrypoint.sh
    restart: unless-stopped
  database:
    image: postgres:latest
    volumes:
      - database_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
        POSTGRES_DB: devops_db
        POSTGRES_USER: wojtek
        POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
volumes:
  database_data: